---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: incident-reporting-ui
    release: v1
  name: incident-reporting-ui-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: incident-reporting-ui
    release: v1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum-keyfile
  labels:
    app: incident-reporting-ui
data:
  UTC--2019-01-03T19-49-59.140692000Z--fe00bb37a56282d33680542ae1cd6763660b4812: |-
    {"address":"fe00bb37a56282d33680542ae1cd6763660b4812","crypto":{"cipher":"aes-128-ctr","ciphertext":"1d895e45c8fdbe13d2f1742e8d8cb2fefa4eb4fe9a64d12205407fcf68860e9c","cipherparams":{"iv":"e2c3fa653da6e4c8349b314c5acaa5d1"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c20d80c7a3a2067aaff15be2750b590787b4c2299a366cd2cf4492521bba44e8"},"mac":"efffe8d06198dea8ff6683f2d199b59429a3f5cc5e2ff4970bbdd4224c146134"},"id":"ac1bf14e-a73d-4859-beb4-879d4a592c9a","version":3}
---
apiVersion: v1
kind: Secret
metadata:
  name: incident-reporting-secrets
  labels:
    app: incident-reporting-ui
data:
  passphrase: YmFuZ2d1bWIw
  user: ZGV2QGJsb2NrY2hhaW4ubG9jYWw=
  password: Vk13YXJlMSE=
  url: bWdtdC5ibG9ja2NoYWluLnZtd2FyZS5jb20vYmxvY2tjaGFpbnMvZGEyZjM4NzctN2M5Ni00ODk5LTgzMjktMjc2MWExNDg2ZmUwL2FwaS9jb25jb3JkL2V0aA==
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: incident-reporting
    release: v1
  name: incident-reporting-ui
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: incident-reporting-ui
      release: v1
  template:
    metadata:
      labels:
        app: incident-reporting-ui
        release: v1
    spec:
      containers:
      - image: docker.io/tompscanlan/ui-server:1.1
        name: ui-server
        # command:
        #   - sleep
        #   - "1000"
        ports:
        - containerPort: 80
        # resources:
        #   limits:
        #     cpu: 200m
        #     memory: 128M
        #   requests:
        #     cpu: 100m
        #     memory: 32M
        volumeMounts:
          - mountPath: /keyfile
            name: ethereum-keyfile-volume
        env: 
          - name: CLIENT_URL
            valueFrom:
              secretKeyRef:
               name: incident-reporting-secrets
               key: url
          - name: CLIENT_USER
            valueFrom:
              secretKeyRef:
               name: incident-reporting-secrets
               key: user
          - name: CLIENT_PASSWORD
            valueFrom:
              secretKeyRef:
               name: incident-reporting-secrets
               key: password
          - name: CLIENT_PASSPHRASE
            valueFrom:
              secretKeyRef:
               name: incident-reporting-secrets
               key: passphrase
          - name: CLIENT_KEYFILE
            value: /keyfile/UTC--2019-01-03T19-49-59.140692000Z--fe00bb37a56282d33680542ae1cd6763660b4812
          - name: CLIENT_CONTRACT_ADDRESS
            value: "0x40565998749204dd8bb74e5db51c77bd3c5f0931"
      volumes:
        - name: ethereum-keyfile-volume
          configMap: 
            name: ethereum-keyfile
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # certmanager.k8s.io/issuer: letsencrypt-stage
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/proxy-body-size: "0"
    # ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    # kubernetes.io/tls-acme: "true"
  labels:
    app: incident-reporting
    release: v1
  name: incident-reporting-ui-ingress
spec:
  rules:
  - host: incident.demo.butterhead.net
    http:
      paths:
      - backend:
          serviceName: incident-reporting-ui-svc
          servicePort: 80
        path: /
  # tls:
  # - hosts:
  #   - incident.demo.butterhead.net
  #   secretName: incident-reporting-ui-cert
